### ISSUE TITLE
리뷰 평점 기준 크롤링에 대하여 

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#26]
정렬하여 구현을 완료하였는데 왼쪽에 이미지가 들어가면 더 좋을 것 같습니다.
혹시 크롤링에 이미지 주소도 포함해주실 수 있으신지 물어보고자 합니다!!

이미지가 들어가면 보는 사람들로 하여금 훨씬 인식하기가 쉬울 것 같습니다!

![image](https://user-images.githubusercontent.com/62468086/143827613-9d858829-7655-4444-a7a8-2ed08dfdca91.png)

**Comment by kwongustj** [comment]
더하여 화면 구성도 풍부해질 것 같습니다.

**Comment by garamse** [comment]
이미지를 넣는게 사용자들이 보기 수월하다는 의견에 저도 동의합니다 추가 하도록 하겠습니다
