### ISSUE TITLE
최종 발표 ppt에 관하여 

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#44]
중간 발표때 제가 발표했던 PPT 목차는 다음과 같습니다.
01. 필요성 
02. Problem 
03. 차별성
04. Solution
05. 카운슬링 결과 적용
06. Evaluation Plan

마지막 최종 발표때는

- 어떻게 구현하였는지를 자세하게 넣고, 
- 구현 영상을 추가로 제작하고자 합니다. 

목차나 최종 발표 때 추가 하면 좋을 것을 추천해주시기 바랍니다.

**Comment by garamse** [comment]
앱 실행 동영상을 만들어 추가하면 좋을것같습니다

**Comment by kwongustj** [comment]
앗 그러면 앱 실행 동영상과 리드미 파일도 추가해야될 것 같네요 확인하였습니다
