### ISSUE TITLE
2021. 12.11 최종 발표전 미팅때 할 것들 정리

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#45]
2021. 12.11 최종 발표전 미팅때 할 것들을 정리해 보았습니다. 추가적으로 해야 할 것이 있으면 말해주시기 바랍니다!!

- 구현은 어느정도 완료 되었으나 중간중간에 오류나는 부분들이 있어 수정할 것
- 최종 결과보고서 작성
- 전체적인 세부사항 수정 & 보완
- 최종 발표 피피티 제작

**Comment by garamse** [comment]
일단 구현 동영상도 추가하여야 하고, 대본도 작성하여야 할 것 같습니다.
또한 교수님께서 수정하라고 하신 직무 보고서도 작성해서 다시 메일로 보내야 할 것 같습니다.

**Comment by kwongustj** [comment]
생각해보니 리드미도 추가해야 할 것 같습니다.
