### ISSUE TITLE
키워드 선택 개수 정하기 

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#46]
키워드 선택을 
1. 같이 온 사람과의 관계
2. 목적이 무엇인지에 대해
3.  목적에 관한 키워드 중 마음에 드는 키워드 선택

이렇게 세개로 나누었습니다.

<img src="https://user-images.githubusercontent.com/62468086/145049262-48d32cec-b79a-46dc-b68d-d932831721ab.png" width="300" height="400"/>
<img src="https://user-images.githubusercontent.com/62468086/145049846-90dcbaf9-42cd-4a99-b63f-2a82fb35ee40.png" width="300" height="400"/>

각각 몇개씩 사용자가 고를 수 있을지에 대해 결정해야 할 것 같습니다.

제 생각은 일단 같이 온 사람과의 관계는 1개만 고르고, 목적은 2개 정도가 나을 것 같습니다. 그리고 마음에 드는 키워드 선택은 8개가 나을 것이라고 생각하는데 어떻게 생각하시나요?

**Comment by garamse** [comment]
다른건 다 괜찮은데 목적은 3개 정도를 하면 너무 많을까요?

**Comment by kwongustj** [comment]
각 목적당 연관 키워드들이 20개정도 되는데 목적을 3개를 선택해버리면 8개만 선택 할 수 있는 선택지가 60개 정도가 됩니다 :-(
이것도 한번 토요일날 만나서 여러 경우로 해보고 상의해보는 것도 좋을  것 같습니다.

**Comment by garamse** [comment]
그럼 일단 현서님 말씀대로 2개로 하여 구현 진행하고, 토요일날 말씀하신대로 상의해보는 게 좋을 것 같습니다.

**Comment by kwongustj** [comment]
넹 그러면 지금은 2개로 진행하겠습니다.
