### ISSUE TITLE
엑셀파일 -> 파이어베이스 저장하는 것이 어떤지에 대해

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#47]
현재 리뷰별 평점이나 키워드 정보가 엑셀파일로 저장되어있는데 파이어베이스의 Realtime Database에 다 올려서
flask로 가져오게 하는 건 어떤지 의견 부탁드립니다.

**Comment by garamse** [comment]
좋다고 생각합니다 !

**Comment by kwongustj** [comment]
그렇다면 가람님이 올리신 엑셀파일을 파이어베이스에 올리도록해서 flask를 통해 값을 가져오는 방식을 하도록 할까요 ??

**Comment by garamse** [comment]
넵넵
