### ISSUE TITLE
마지막 결과페이지 논의 사항

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#48]
마지막 결과페이지에서 몇개의 상점 및 편의 시설을 추천해줘야 할지 논의해야 할 것 같습니다.
5개정도면 충분할 것이라고 생각되는데 어떻게 생각 하시나요?
그 이하면 너무 사용자의 선택범위가 적은 것 같고 그 이상이면 많아 보입니다.

**Comment by garamse** [comment]
네 저도 5개면 충분할 것 같다고 생각합니다!

**Comment by kwongustj** [comment]
그럼 마지막에 보여지는 결과 페이지는 5개로 하는 것으로 결정 하겠습니다~
