### ISSUE TITLE
깃허브 이슈 comment시 오류 발생 (You can't comment at this time)

### ISSUE THREAD

**Issue by garamse** [kwongustj/project_comehere#49]
이슈 글에서 이미지에 나온 것과 같이 You can't comment at this time이라는 에러가 뜹니다. 이유가 무엇인지 아시나요 ??

![image](https://user-images.githubusercontent.com/75787973/145347860-fc89d981-ff86-4b35-a573-fd238e21a0d0.png)

**Comment by kwongustj** [comment]
인터넷에서 확인해보니 광고차단기,,를 확인해보라고 나오네요..
혹시 폰말고 노트북으로 직접 해보시면 어떠실까요??

**Comment by garamse** [comment]
앗 노트북으로 하니 실행되네요. 감사합니다.
