### ISSUE TITLE
점포명이 다른 문제

### ISSUE THREAD

**Issue by kwongustj** [kwongustj/project_comehere#52]
네이버에서 리뷰를 크롤링할 때의 점포명과 현대백화점 홈페이지 상에 있는 점포명이 상이합니다.
그래서 점포를 찾을 때 오류가 발생하는 것 같습니다.
엑셀 파일에 있는 점포명을 현대백화점상에 있는 점포명으로 바꿔줘야 할 것 같습니다.

내일까지 해주시면 될 것 같습니다!!

**Comment by garamse** [comment]
아 그럼 엑셀파일 수정해서 보내드리도록 하겠습니다!!

**Comment by kwongustj** [comment]
넵 알겠습니다.
