### ISSUE TITLE
앱 보완했으면 좋겠는 부분

### ISSUE THREAD

**Issue by garamse** [kwongustj/project_comehere#55]
해당 캡쳐 부분이 점포 평점 리뷰로 위로 올리는 부분인데, 색깔이 겹치고 글씨도 겹쳐 조금 보기 어려운 것 같습니다. 
색깔을 수정하는 것은 어떤가요??

![image](https://user-images.githubusercontent.com/75787973/145551492-682cd422-56f7-4f32-a1dc-541a37b2363a.png)

**Comment by kwongustj** [comment]
앗 알겠습니다. 저도 인지하고 있던 부분입니다. 색깔이랑 글씨 부분 색깔 정해서 변경해보겠습니다.

**Comment by kwongustj** [comment]
수정하였습니다.

![image](https://user-images.githubusercontent.com/62468086/145666381-d47b9d69-a1cf-4a70-bd76-b7f3c1f52030.png)
