### ISSUE TITLE
카운슬링 결과에 대한 적용 (데이터 수집 방법)

### ISSUE THREAD

**Issue by garamse** [kwongustj/project_comehere#9]
오늘 멘토님과 멘토링을 하였는데 키워드에 대한 데이터수집을 어떻게 하면 좋을지 각자 의견을 말씀해주세요
저는 네이버 리뷰들을 크롤링 할 생각이고 된다면 블로그 리뷰들도 크롤링하여 이 두가지 방법으로 데이터를 수집 할 생각입니다.

**Comment by kwongustj** [comment]
요즘 많은 사람들이 인스타그램 등 sns를 사용하니 거기서 크롤링 하는 것도 좋은 것 같습니다. 제가 인스타그램 크롤링을 하여 키워드에 대한 데이터 수집에 같이 참여 하겠습니다!
